# Generated by Django 4.0.1 on 2022-01-22 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='user',
        ),
    ]
