# Generated by Django 4.0.1 on 2022-01-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_artwork_total_votes_question_total_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='total_votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='total_votes',
        ),
    ]
