# Generated by Django 4.0.1 on 2022-01-31 21:23

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_artwork_total_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='mediafile',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.upload_to),
        ),
        migrations.AlterField(
            model_name='question',
            name='mediafile',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.upload_to),
        ),
    ]
