# Generated by Django 4.0.1 on 2022-02-01 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_alter_artwork_mediafile_alter_question_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='artwork_save', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='question_save', to=settings.AUTH_USER_MODEL),
        ),
    ]
