# Generated by Django 4.0.1 on 2022-01-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
