# Generated by Django 4.0.1 on 2022-01-30 23:18

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=profiles.models.upload_to),
        ),
    ]
