# Generated by Django 4.0.1 on 2022-01-23 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendes',
            field=models.ManyToManyField(blank=True, related_name='event_ttend', to=settings.AUTH_USER_MODEL),
        ),
    ]
