# Generated by Django 4.0.1 on 2022-01-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_rename_attendes_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
