# Generated by Django 4.0.1 on 2022-01-30 23:40

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_author_article_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=articles.models.editor_upload_to)),
            ],
        ),
    ]
