# Generated by Django 4.0.1 on 2022-02-01 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_editorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='article_save', to=settings.AUTH_USER_MODEL),
        ),
    ]
