# Generated by Django 4.0.1 on 2022-01-22 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_remove_vote_recipient_remove_vote_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='timestamp',
            new_name='created',
        ),
    ]
