# Generated by Django 4.0.1 on 2022-01-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='sender',
        ),
    ]
