# Generated by Django 4.0.1 on 2022-01-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_event_attendes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='attendes',
            new_name='attendees',
        ),
    ]
