# Generated by Django 4.0.1 on 2022-01-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('upvote', 'like'), ('downvote', 'like'), ('comment', 'comment'), ('follow', 'follow')], max_length=10),
        ),
    ]
